### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by francicco** [tanghaibao/jcvi#160]
Hi,

I'm trying to install the jcvi package. Running the test analysis I got these errors:

```
(AllMapsEnv) [tk19812@bc4login1 ALLMAPS-testdata]$ ./run.sh 
22:33:31 [allmaps] A total of 120 markers written to `JM-2.bed`.
22:33:31 [allmaps] Weights file `weights.txt` found. Will not overwrite.
22:33:32 [base] Load file `JM-2.bed`
22:33:32 [allmaps] Map contains 120 markers in 2 linkage groups.
22:33:32 [allmaps] Retained 120 of 120 (100.0%) clean markers.
22:33:32 [base] Load file `weights.txt`
22:33:32 [base] Imported 2 records from `weights.txt`.
22:33:32 [allmaps] Map weights: dict_items([('JMFemale', 1), ('JMMale', 1)])
22:33:32 [allmaps] Linkage function: double-linkage
22:33:32 [allmaps] Partition LGs based on JMFemale
22:33:32 [base] Load file `scaffolds.fasta.sizes`
22:33:32 [allmaps] Working on JMMale-23|JMFemale-23 ...
22:33:32 [allmaps] Graph size: |V|=24, |E|=474.
22:33:32 [allmaps] concorde-TSP failed. Use default scaffold ordering.
22:33:32 [allmaps] Start EC round 0
22:33:32 [ec] GA setup: ngen=500 npop=100 cpus=16 seed=666
Current iteration 20: max_score=(71.0,)
Current iteration 40: max_score=(79.0,)
Current iteration 60: max_score=(83.0,)
Current iteration 80: max_score=(86.0,)
Current iteration 100: max_score=(87.0,)
Current iteration 120: max_score=(88.0,)
Current iteration 140: max_score=(88.0,)
Current iteration 160: max_score=(89.0,)
Current iteration 180: max_score=(89.0,)
Current iteration 200: max_score=(89.0,)
Current iteration 220: max_score=(89.0,)
Current iteration 240: max_score=(89.0,)
Current iteration 260: max_score=(89.0,)
Current iteration 280: max_score=(89.0,)
Current iteration 300: max_score=(89.0,)
Current iteration 320: max_score=(89.0,)
Current iteration 340: max_score=(89.0,)
Current iteration 360: max_score=(89.0,)
Current iteration 380: max_score=(89.0,)
Current iteration 400: max_score=(89.0,)
Current iteration 420: max_score=(89.0,)
Current iteration 440: max_score=(89.0,)
Current iteration 460: max_score=(89.0,)
Current iteration 480: max_score=(89.0,)
Current iteration 500: max_score=(89.0,)
Current iteration 520: max_score=(89.0,)
Current iteration 540: max_score=(89.0,)
Current iteration 560: max_score=(89.0,)
Current iteration 580: max_score=(89.0,)
Current iteration 600: max_score=(89.0,)
Current iteration 620: max_score=(89.0,)
Current iteration 640: max_score=(89.0,)
22:33:35 [allmaps] Fixed orientations for 1 scaffolds.
22:33:35 [allmaps] Current best fitness: (89.0,)
22:33:35 [allmaps] Start EC round 1
/mnt/storage/scratch/tk19812/software/jcvi/AllMapsEnv/lib/python3.7/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'FitnessMax' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/mnt/storage/scratch/tk19812/software/jcvi/AllMapsEnv/lib/python3.7/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'Individual' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
22:33:35 [ec] GA setup: ngen=500 npop=100 cpus=16 seed=666
Current iteration 20: max_score=(89.0,)
Current iteration 40: max_score=(89.0,)
Current iteration 60: max_score=(89.0,)
Current iteration 80: max_score=(89.0,)
Current iteration 100: max_score=(89.0,)
Current iteration 120: max_score=(89.0,)
Current iteration 140: max_score=(89.0,)
Current iteration 160: max_score=(89.0,)
Current iteration 180: max_score=(89.0,)
Current iteration 200: max_score=(89.0,)
Current iteration 220: max_score=(89.0,)
Current iteration 240: max_score=(89.0,)
Current iteration 260: max_score=(89.0,)
Current iteration 280: max_score=(89.0,)
Current iteration 300: max_score=(89.0,)
Current iteration 320: max_score=(89.0,)
Current iteration 340: max_score=(89.0,)
Current iteration 360: max_score=(89.0,)
Current iteration 380: max_score=(89.0,)
Current iteration 400: max_score=(89.0,)
Current iteration 420: max_score=(89.0,)
Current iteration 440: max_score=(89.0,)
Current iteration 460: max_score=(89.0,)
Current iteration 480: max_score=(89.0,)
Current iteration 500: max_score=(89.0,)
22:33:37 [allmaps] No fitness improvement: (89.0,). Exit EC.
22:33:37 [allmaps] Dropped 0 minor scaffolds
>chr23 (JMMale-23|JMFemale-23) FINAL
scaffold_158? scaffold_1006? scaffold_382- scaffold_648? scaffold_829+ scaffold_642? scaffold_513+ scaffold_331? scaffold_150+ scaffold_80+ scaffold_43+ scaffold_129- scaffold_164+ scaffold_225? scaffold_148+ scaffold_95? scaffold_310+ scaffold_375+ scaffold_792? scaffold_1189+ scaffold_866? scaffold_821?
22:33:37 [allmaps] AGP file written to `JM-2.chr.agp`.
22:33:37 [allmaps] Tour file written to `JM-2.tour`.
22:33:37 [base] Load file `JM-2.chr.agp`
22:33:37 [base] Load file `scaffolds.fasta`
22:33:38 [agp] Write object chr23 to `JM-2.chr.fasta`
22:33:38 [agp] Target fasta written to `JM-2.chr.fasta`.
22:33:38 [base] Load file `JM-2.chr.agp`
22:33:38 [base] Load file `scaffolds.fasta.sizes`
22:33:38 [allmaps] Write unplaced AGP to `JM-2.unplaced.agp`.
22:33:38 [base] Load file `JM-2.unplaced.agp`
22:33:38 [base] Load file `scaffolds.fasta`
22:33:38 [agp] Target fasta written to `JM-2.unplaced.fasta`.
22:33:38 [base] cat JM-2.chr.agp JM-2.unplaced.agp >JM-2.agp
22:33:38 [base] cat JM-2.chr.fasta JM-2.unplaced.fasta >JM-2.fasta
22:33:38 [base] Load file `JM-2.agp`
22:33:38 [base] Load file `scaffolds.fasta.sizes`
22:33:38 [base] faSize -detailed /mnt/storage/scratch/tk19812/software/jcvi/ALLMAPS-testdata/JM-2.fasta >JM-2.fasta.sizes
22:33:38 [base] Load file `JM-2.fasta.sizes`
22:33:38 [chain] File written to `JM-2.chain`.
22:33:38 [base] liftOver -minMatch=1 JM-2.bed JM-2.chain JM-2.lifted.bed unmapped
Reading liftover chains
Mapping coordinates
22:33:38 [base] sort -k1,1 -k2,2n -k3,3n -k4,4 JM-2.lifted.bed -o JM-2.lifted.bed
22:33:38 [base] Load file `JM-2.bed`
22:33:38 [allmaps] Map contains 120 markers in 2 linkage groups.
22:33:38 [base] Load file `scaffolds.fasta.sizes`
22:33:38 [base] Load file `JM-2.chr.agp`
22:33:38 [base] Load file `JM-2.chr.agp`
22:33:38 [base] Load file `JM-2.lifted.bed`
22:33:38 [allmaps] Map contains 120 markers in 2 linkage groups.
22:33:38 [base] Load file `weights.txt`
22:33:38 [base] Imported 2 records from `weights.txt`.
22:33:38 [allmaps] Map weights: dict_items([('JMFemale', 1), ('JMMale', 1)])
22:33:38 [base] Load file `JM-2.agp`
22:33:38 [base] savefig failed. Reset usetex to False.
Failed to process string with tex because latex could not be found
22:33:38 [font_manager] findfont: Font family ['sans-serif'] not found. Falling back to DejaVu Sans.
22:33:38 [font_manager] findfont: Font family ['sans-serif'] not found. Falling back to DejaVu Sans.
Traceback (most recent call last):
  File "/mnt/storage/scratch/tk19812/software/jcvi/AllMapsEnv/lib/python3.7/site-packages/matplotlib/texmanager.py", line 304, in _run_checked_subprocess
    stderr=subprocess.STDOUT)
  File "/mnt/storage/software/languages/anaconda/Anaconda3-2019.03/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/mnt/storage/software/languages/anaconda/Anaconda3-2019.03/lib/python3.7/subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/mnt/storage/software/languages/anaconda/Anaconda3-2019.03/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/mnt/storage/software/languages/anaconda/Anaconda3-2019.03/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'latex': 'latex'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/home/tk19812/scratch/software/jcvi/jcvi/graphics/base.py", line 183, in savefig
    plt.savefig(figname, dpi=dpi, format=format)
  File "/mnt/storage/scratch/tk19812/software/jcvi/AllMapsEnv/lib/python3.7/site-packages/matplotlib/pyplot.py", line 722, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/mnt/storage/scratch/tk19812/software/jcvi/AllMapsEnv/lib/python3.7/site-packages/matplotlib/figure.py", line 2180, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/mnt/storage/scratch/tk19812/software/jcvi/AllMapsEnv/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2082, in print_figure
    **kwargs)
  File "/mnt/storage/scratch/tk19812/software/jcvi/AllMapsEnv/lib/python3.7/site-packages/matplotlib/backends/backend_pdf.py", line 2503, in print_pdf
    self.figure.draw(renderer)
  File "/mnt/storage/scratch/tk19812/software/jcvi/AllMapsEnv/lib/python3.7/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/mnt/storage/scratch/tk19812/software/jcvi/AllMapsEnv/lib/python3.7/site-packages/matplotlib/figure.py", line 1709, in draw
    renderer, self, artists, self.suppressComposite)
  File "/mnt/storage/scratch/tk19812/software/jcvi/AllMapsEnv/lib/python3.7/site-packages/matplotlib/image.py", line 135, in _draw_list_compositing_images
    a.draw(renderer)
  File "/mnt/storage/scratch/tk19812/software/jcvi/AllMapsEnv/lib/python3.7/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/mnt/storage/scratch/tk19812/software/jcvi/AllMapsEnv/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 2607, in draw
    self._update_title_position(renderer)
  File "/mnt/storage/scratch/tk19812/software/jcvi/AllMapsEnv/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 2549, in _update_title_position
    bb = ax.xaxis.get_tightbbox(renderer)
  File "/mnt/storage/scratch/tk19812/software/jcvi/AllMapsEnv/lib/python3.7/site-packages/matplotlib/axis.py", line 1164, in get_tightbbox
    self._update_label_position(renderer)
  File "/mnt/storage/scratch/tk19812/software/jcvi/AllMapsEnv/lib/python3.7/site-packages/matplotlib/axis.py", line 2014, in _update_label_position
    bboxes, bboxes2 = self._get_tick_boxes_siblings(renderer=renderer)
  File "/mnt/storage/scratch/tk19812/software/jcvi/AllMapsEnv/lib/python3.7/site-packages/matplotlib/axis.py", line 1999, in _get_tick_boxes_siblings
    tlb, tlb2 = axx.xaxis._get_tick_bboxes(ticks_to_draw, renderer)
  File "/mnt/storage/scratch/tk19812/software/jcvi/AllMapsEnv/lib/python3.7/site-packages/matplotlib/axis.py", line 1150, in _get_tick_bboxes
    for tick in ticks if tick.label1.get_visible()],
  File "/mnt/storage/scratch/tk19812/software/jcvi/AllMapsEnv/lib/python3.7/site-packages/matplotlib/axis.py", line 1150, in <listcomp>
    for tick in ticks if tick.label1.get_visible()],
  File "/mnt/storage/scratch/tk19812/software/jcvi/AllMapsEnv/lib/python3.7/site-packages/matplotlib/text.py", line 890, in get_window_extent
    bbox, info, descent = self._get_layout(self._renderer)
  File "/mnt/storage/scratch/tk19812/software/jcvi/AllMapsEnv/lib/python3.7/site-packages/matplotlib/text.py", line 291, in _get_layout
    ismath="TeX" if self.get_usetex() else False)
  File "/mnt/storage/scratch/tk19812/software/jcvi/AllMapsEnv/lib/python3.7/site-packages/matplotlib/backends/_backend_pdf_ps.py", line 47, in get_text_width_height_descent
    s, fontsize, renderer=self)
  File "/mnt/storage/scratch/tk19812/software/jcvi/AllMapsEnv/lib/python3.7/site-packages/matplotlib/texmanager.py", line 448, in get_text_width_height_descent
    dvifile = self.make_dvi(tex, fontsize)
  File "/mnt/storage/scratch/tk19812/software/jcvi/AllMapsEnv/lib/python3.7/site-packages/matplotlib/texmanager.py", line 338, in make_dvi
    texfile], tex)
  File "/mnt/storage/scratch/tk19812/software/jcvi/AllMapsEnv/lib/python3.7/site-packages/matplotlib/texmanager.py", line 308, in _run_checked_subprocess
    'found'.format(command[0])) from exc
RuntimeError: Failed to process string with tex because latex could not be found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/scratch/tk19812/software/jcvi/AllMapsEnv/lib/python3.7/site-packages/matplotlib/texmanager.py", line 304, in _run_checked_subprocess
    stderr=subprocess.STDOUT)
  File "/mnt/storage/software/languages/anaconda/Anaconda3-2019.03/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/mnt/storage/software/languages/anaconda/Anaconda3-2019.03/lib/python3.7/subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/mnt/storage/software/languages/anaconda/Anaconda3-2019.03/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/mnt/storage/software/languages/anaconda/Anaconda3-2019.03/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'latex': 'latex'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/software/languages/anaconda/Anaconda3-2019.03/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/mnt/storage/software/languages/anaconda/Anaconda3-2019.03/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mnt/storage/home/tk19812/scratch/software/jcvi/jcvi/assembly/allmaps.py", line 1872, in <module>
    main()
  File "/mnt/storage/home/tk19812/scratch/software/jcvi/jcvi/assembly/allmaps.py", line 828, in main
    p.dispatch(globals())
  File "/mnt/storage/home/tk19812/scratch/software/jcvi/jcvi/apps/base.py", line 100, in dispatch
    globals[action](sys.argv[2:])
  File "/mnt/storage/home/tk19812/scratch/software/jcvi/jcvi/assembly/allmaps.py", line 1526, in path
    "--figsize={0}".format(opts.figsize)])
  File "/mnt/storage/home/tk19812/scratch/software/jcvi/jcvi/assembly/allmaps.py", line 1868, in plotall
    plot(xargs + [seqid])
  File "/mnt/storage/home/tk19812/scratch/software/jcvi/jcvi/assembly/allmaps.py", line 1843, in plot
    savefig(image_name, dpi=iopts.dpi, iopts=iopts)
  File "/mnt/storage/home/tk19812/scratch/software/jcvi/jcvi/graphics/base.py", line 189, in savefig
    plt.savefig(figname, dpi=dpi)
  File "/mnt/storage/scratch/tk19812/software/jcvi/AllMapsEnv/lib/python3.7/site-packages/matplotlib/pyplot.py", line 722, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/mnt/storage/scratch/tk19812/software/jcvi/AllMapsEnv/lib/python3.7/site-packages/matplotlib/figure.py", line 2180, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/mnt/storage/scratch/tk19812/software/jcvi/AllMapsEnv/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2082, in print_figure
    **kwargs)
  File "/mnt/storage/scratch/tk19812/software/jcvi/AllMapsEnv/lib/python3.7/site-packages/matplotlib/backends/backend_pdf.py", line 2503, in print_pdf
    self.figure.draw(renderer)
  File "/mnt/storage/scratch/tk19812/software/jcvi/AllMapsEnv/lib/python3.7/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/mnt/storage/scratch/tk19812/software/jcvi/AllMapsEnv/lib/python3.7/site-packages/matplotlib/figure.py", line 1709, in draw
    renderer, self, artists, self.suppressComposite)
  File "/mnt/storage/scratch/tk19812/software/jcvi/AllMapsEnv/lib/python3.7/site-packages/matplotlib/image.py", line 135, in _draw_list_compositing_images
    a.draw(renderer)
  File "/mnt/storage/scratch/tk19812/software/jcvi/AllMapsEnv/lib/python3.7/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/mnt/storage/scratch/tk19812/software/jcvi/AllMapsEnv/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 2647, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/mnt/storage/scratch/tk19812/software/jcvi/AllMapsEnv/lib/python3.7/site-packages/matplotlib/image.py", line 135, in _draw_list_compositing_images
    a.draw(renderer)
  File "/mnt/storage/scratch/tk19812/software/jcvi/AllMapsEnv/lib/python3.7/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/mnt/storage/scratch/tk19812/software/jcvi/AllMapsEnv/lib/python3.7/site-packages/matplotlib/text.py", line 714, in draw
    mtext=mtext)
  File "/mnt/storage/scratch/tk19812/software/jcvi/AllMapsEnv/lib/python3.7/site-packages/matplotlib/backends/backend_pdf.py", line 1893, in draw_tex
    dvifile = texmanager.make_dvi(s, fontsize)
  File "/mnt/storage/scratch/tk19812/software/jcvi/AllMapsEnv/lib/python3.7/site-packages/matplotlib/texmanager.py", line 338, in make_dvi
    texfile], tex)
  File "/mnt/storage/scratch/tk19812/software/jcvi/AllMapsEnv/lib/python3.7/site-packages/matplotlib/texmanager.py", line 308, in _run_checked_subprocess
    'found'.format(command[0])) from exc
RuntimeError: Failed to process string with tex because latex could not be found
```

Any help to fix it?
Thanks a lot
F

**Comment by tanghaibao** [comment]
@francicco 

This is perhaps the most asked issue for this repo.

Try google on how to install Latex (it was only an optional requirement before when ALLMAPS was developed a few years ago, however, matplotlib has changed its way to interact with latex in recent versions, so it's emitting this error). 

Please take a look at [Get LaTeX](https://www.latex-project.org/get/) for various options for each major OS. For example, on Debian-like Linux OS you can often do:

```console
sudo apt-get install -y texlive texlive-latex-extra texlive-latex-recommended
```

Haibao

**Comment by francicco** [comment]
Hi Haibao,

I fixed that but apparently the syntax of the new version is changed. I used to execute these commands:

```
python -m jcvi.compara.synteny depth --histogram $SPECIES.$REFSP.anchors
python -m jcvi.assembly.syntenypath bed $SPECIES.$REFSP.anchors -o $SPECIES.synteny.bed
python -m jcvi.assembly.allmaps mergebed $SPECIES.synteny.bed -o $SPECIES.scaff.bed
python -m jcvi.assembly.allmaps path --cpus=$THREADS --links=100 --renumber --ngen=1000 $SPECIES.scaff.bed $ASSEMBLY.fasta
```

for example, the first command (synteny depth) returns this error:

```
/mnt/storage/home/tk19812/scratch/software/jcvi/jcvi/compara/synteny.py:10: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Iterable, defaultdict
09:44:47 [blast] Fall back to Python implementation of BlastLine
09:44:47 [synteny] Assuming --qbed=Haoe.bed --sbed=Hmel.bed
09:44:47 [base] Load file `Haoe.bed`
09:44:47 [base] Load file `Hmel.bed`
09:44:47 [base] Load file `Haoe.Hmel.anchors`
Genome Haoe depths:
Depth 0: 12,545 of 22,225 (56.4%)
Depth 1: 9,680 of 22,225 (43.6%)
Genome Hmel depths:
Depth 0: 8,164 of 19,480 (41.9%)
Depth 1: 10,764 of 19,480 (55.3%)
Depth 2: 496 of 19,480 (2.5%)
Depth 3: 46 of 19,480 (0.2%)
Depth 4: 6 of 19,480 (0.0%)
Depth 5: 4 of 19,480 (0.0%)
Traceback (most recent call last):
  File "/mnt/storage/software/languages/anaconda/Anaconda3-2019.03/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/mnt/storage/software/languages/anaconda/Anaconda3-2019.03/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mnt/storage/home/tk19812/scratch/software/jcvi/jcvi/compara/synteny.py", line 1550, in <module>
    main()
  File "/mnt/storage/home/tk19812/scratch/software/jcvi/jcvi/compara/synteny.py", line 487, in main
    p.dispatch(globals())
  File "/mnt/storage/home/tk19812/scratch/software/jcvi/jcvi/apps/base.py", line 100, in dispatch
    globals[action](sys.argv[2:])
  File "/mnt/storage/home/tk19812/scratch/software/jcvi/jcvi/compara/synteny.py", line 1350, in depth
    xmax = opts.xmax or max(4, max(dsq.keys() + dss.keys()))
TypeError: unsupported operand type(s) for +: 'dict_keys' and 'dict_keys'
```

Any help?
Thank you
F

**Comment by tanghaibao** [comment]
@francicco 

Thanks for reporting the issue. As I am starting to move the repo to Python 3, we are expecting a number of bugs, and this is one of them. I think I have fixed the issue in 7150682 and have added tests.

Please pull from the repo and see if the issues persist.

Thanks,
Haibao

**Comment by DieTANG** [comment]
Hi, Haibao,
I have the latex errors when I running the test analysis
`RuntimeError: Failed to process string with tex because latex could not be found`
I installed latex by `pip install latex` but not working.
I have no sudo authority, and using python3.7, what can I do to fix this bug?
Thanks!

**Comment by ShawnWx2019** [comment]
Hi Prof. Tang
I have installed **MacTex** on MacOS, but it still not work, with 
```bash
20:20:54 [base] savefig failed. Reset usetex to False.
[Errno 2] No such file or directory: 'latex'
---
OSError: [Errno 2] No such file or directory: 'latex'
```
and the dotplot pdf file was broken. Do you have any suggestion？
Thanks！

**Comment by tanghaibao** [comment]
@DieTANG @ShawnWx2019 

You are missing LaTex, which can be installed [here](https://www.latex-project.org/get/).

Haibao

**Comment by ShawnWx2019** [comment]
Hi prof. Tang
Thanks for your reply, it is really weird, 
- **First**, I tried `latex --help`, nothing happend, than I **completely uninstalled** `MacTex` followed the [Uninstalling TeX](http://www.tug.org/mactex/uninstalling.html) steps and **reinstalled** MacTex, the `latex --help` worked;
- **Second**, I removed the jcvi conda env than reinstalled jcvi with pip:
```
pip install jcvi
```
**Finally Jcvi worked.**
Thank you again.
best wishes.

**Comment by Qiaojilim** [comment]
@francicco 
hello, could you give me some hint about how did you solve the latex problem? I meet with the same issue on my mac os system. appreciate it

Lim

**Comment by ShawnWx2019** [comment]
> @francicco
> hello, could you give me some hint about how did you solve the latex problem? I meet with the same issue on my mac os system. appreciate it
> 
> Lim
I record the solution in：
[My blog](https://shawnmagic.gitee.io/blog/2020/04/02/undefined.html)

**Comment by Qiaojilim** [comment]
> @francicco
> hello, could you give me some hint about how did you solve the latex problem? I meet with the same issue on my mac os system. appreciate it
> 
> Lim
> I record the solution in：
> [My blog](https://shawnmagic.gitee.io/blog/2020/04/02/undefined.html)

@ShawnWx2019 
Thanks a lot, will check that soon. Nice day
:-)

**Comment by Qiaojilim** [comment]
> > @francicco
> > hello, could you give me some hint about how did you solve the latex problem? I meet with the same issue on my mac os system. appreciate it
> > Lim
> > I record the solution in：
> > [My blog](https://shawnmagic.gitee.io/blog/2020/04/02/undefined.html)
> 
> @ShawnWx2019
> Thanks a lot, will check that soon. Nice day
> :-)

I just figured out my issue. My sol is to add my executable MacTex to my PATH. Then it works perfectly. Thanks for your reply

**Comment by ShawnWx2019** [comment]
> > > @francicco
> > > hello, could you give me some hint about how did you solve the latex problem? I meet with the same issue on my mac os system. appreciate it
> > > Lim
> > > I record the solution in：
> > > [My blog](https://shawnmagic.gitee.io/blog/2020/04/02/undefined.html)
> > 
> > 
> > @ShawnWx2019
> > Thanks a lot, will check that soon. Nice day
> > :-)
> 
> I just figured out my issue. My sol is to add my executable MacTex to my PATH. Then it works perfectly. Thanks for your reply

Thanks！
